/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadevclassobj;

import javax.swing.JOptionPane;


public class MainScrn extends javax.swing.JFrame {

    //private javadevClassobj.BoardPanel game;
    
    //declares all the fields
    String p1NameGS;
    String p2NameGS;
    String TimeOut;
    private PlayerData player1OBJ = null;
    private PlayerData player2OBJ = null;
    
     //declares new MyDBManager named db for PlayerStats class
     private MyDBManager db = new MyDBManager(); 
    //takes in Player names from the Change player name frame
    public MainScrn(String P1InName, String P2InName, PlayerData player1Data, PlayerData player2Data)
    {
        //initialises components
        initComponents();
        //Sets the P1 name variable
        p1NameGS = P1InName;
        //Sets the p2 name variable
        p2NameGS = P2InName;
        //sets the specified background colour that is alligned to the sprites
        getContentPane().setBackground(new java.awt.Color(117, 117, 117)); 
        //sets the player 1 object
        player1OBJ = player1Data;
        //sets the player 2 object
        player2OBJ = player2Data;
       
    }
    //used to get data from the frame
    public void update(String s, int BScore, int YScore)
    {
        //Sets the text of the labe,
        SelectedPiece.setText(s);
        //Sets the Blue score
        BlScore.setText("Blue Score: " + BScore);
        //Sets the Yellow score
        YeScore.setText("Yellow Score: " + YScore);
        //System.out.println(BScore);
        //System.out.println(YScore);
        
        if (YScore > 999)
        {
            //Creates a new Player object to be sent to the DB
                PlayerData NewPlayer = new PlayerData(player1OBJ.getPlayerName(), player1OBJ.getPDOB(), player1OBJ.getPWins() + 1, player1OBJ.getPLosses(),player1OBJ.getPDraws());
                //Sends the new Player to the DB Manager
                db.addPlayer(NewPlayer);
                db.deletePlayer(player1OBJ.getPlayerID());
                JOptionPane.showMessageDialog(null, "Player 1 won");
                //creates a new instance of the selected form, 
                //in this case the home screen
                new HomeScreen().setVisible(true);
                //Disposes/closes the form that is currently open
                this.dispose(); 
        }
        if (BScore > 999)
        {
                //Creates a new Player object to be sent to the DB
                PlayerData NewPlayer = new PlayerData(player2OBJ.getPlayerName(), player2OBJ.getPDOB(), player2OBJ.getPWins() + 1, player2OBJ.getPLosses(),player2OBJ.getPDraws());
                //Sends the new Player to the DB Manager
                db.addPlayer(NewPlayer);
                db.deletePlayer(player1OBJ.getPlayerID());
                JOptionPane.showMessageDialog(null, "Player 2 won");
                //creates a new instance of the selected form, 
                //in this case the home screen
                new HomeScreen().setVisible(true);
                //Disposes/closes the form that is currently open
                this.dispose(); 
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab1 = new javax.swing.JLabel();
        Board = new BoardPanel(this);
        btn_ExitGameState = new javax.swing.JButton();
        Player1GameStateName = new javax.swing.JLabel();
        lblPlayer2GameStateName = new javax.swing.JLabel();
        GameStateTimeOut = new javax.swing.JLabel();
        SelectedPiece = new javax.swing.JLabel();
        DoNot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        YeScore = new javax.swing.JLabel();
        BlScore = new javax.swing.JLabel();

        lab1.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout BoardLayout = new javax.swing.GroupLayout(Board);
        Board.setLayout(BoardLayout);
        BoardLayout.setHorizontalGroup(
            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        BoardLayout.setVerticalGroup(
            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        btn_ExitGameState.setText("Exit Game");
        btn_ExitGameState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitGameStateActionPerformed(evt);
            }
        });

        Player1GameStateName.setText("Player 1 Name");

        lblPlayer2GameStateName.setText("Player 2 Name");

        GameStateTimeOut.setText("jLabel1");

        SelectedPiece.setText("None");

        DoNot.setText("Do not attempt to move till piece selected");

        jLabel1.setText("Selected:");

        YeScore.setText("Yellow score");

        BlScore.setText("Blue Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_ExitGameState, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(GameStateTimeOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SelectedPiece, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(DoNot))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1GameStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlScore, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer2GameStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YeScore, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1GameStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlScore))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DoNot)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GameStateTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectedPiece)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ExitGameState)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer2GameStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(YeScore))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitGameStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitGameStateActionPerformed
        //creates a new instance of the selected form, 
        //in this case the home screen
        new HomeScreen().setVisible(true); 
        //Disposes/closes the form that is currently open
        this.dispose(); 
    }//GEN-LAST:event_btn_ExitGameStateActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //sets the Player 1 name to the inputted name
        Player1GameStateName.setText(p1NameGS);
        //Sets the Player two name to the inputted name
        lblPlayer2GameStateName.setText(p2NameGS);    
        
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                //Declares a new Board Panel
                BoardPanel Board = new BoardPanel();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlScore;
    public javax.swing.JPanel Board;
    private javax.swing.JLabel DoNot;
    private javax.swing.JLabel GameStateTimeOut;
    private javax.swing.JLabel Player1GameStateName;
    private javax.swing.JLabel SelectedPiece;
    private javax.swing.JLabel YeScore;
    private javax.swing.JButton btn_ExitGameState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lblPlayer2GameStateName;
    // End of variables declaration//GEN-END:variables
}
